name: Ejecutar buscador de masías

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Mostrar ruta actual
        run: pwd && ls -la

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Crear archivo JSON
        run: |
          echo "${{ secrets.GSA_JSON }}" > gsa_json.json

      - name: Ejecutar scraper
        working-directory: ./buscador-masias
        run: python scraper.py

