name: Ejecutar buscador de masías

on:
  schedule:
    - cron: "0 7 * * *"   # Todos los días a las 9:00 hora España
  workflow_dispatch:      # Permite ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Descargar el repositorio en la raíz del runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .   # Clona el repo directamente en la raíz del runner

      # Instalar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Instalar dependencias
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      # Crear archivo JSON desde secret
      - name: Crear archivo JSON
        run: |
          echo "${{ secrets.GSA_JSON }}" > gsa_json.json

      # Ejecutar scraper
    - name: Ejecutar scraper
  run: python ./buscador-masias/scraper.py

